In [3]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [4]:
data=pd.read_csv("station2_label_front.txt")

In [5]:
data

        -5.745000  16.014999  -1.555000  9.000000
0          -5.745  16.016001     -1.566         9
1          -5.743  16.011999     -1.562         9
2          -5.743  16.017000     -1.550         9
3          -5.736  16.011000     -1.566         9
4          -5.734  16.004000     -1.555         9
5          -5.734  16.009001     -1.561         9
6          -5.733  15.983000     -1.570         9
7          -5.731  16.016001     -1.567         9
8          -5.731  16.020000     -1.563         9
9          -5.730  15.998000     -1.571         9
10         -5.729  16.014000     -1.573         9
11         -5.727  15.966000     -1.586         9
12         -5.727  15.986000     -1.576         9
13         -5.726  15.962000     -1.580         9
14         -5.725  15.957000     -1.573         9
15         -5.722  15.953000     -1.591         9
16         -5.722  16.011999     -1.566         9
17         -5.721  15.990000     -1.577         9
18         -5.721  15.993000     -1.583         9
19         -5.721  16.004999     -1.572         9
20         -5.719  15.940000     -1.595         9
21         -5.718  16.024000     -1.550         9
22         -5.718  16.025000     -1.567         9
23         -5.715  15.992000     -1.578         9
24         -5.715  16.011999     -1.556         9
25         -5.713  15.987000     -1.583         9
26         -5.713  16.006001     -1.572         9
27         -5.713  16.007000     -1.578         9
28         -5.712  16.021000     -1.562         9
29         -5.711  15.945000     -1.578         9
...           ...        ...        ...       ...
518452      1.393  14.039000     -2.005         9
518453      1.393  14.104000     -1.989         9
518454      1.394  14.054000     -1.996         9
518455      1.394  14.107000     -1.983         9
518456      1.394  14.113000     -1.978         9
518457      1.396  14.068000     -1.993         9
518458      1.398  14.090000     -1.992         9
518459      1.398  14.102000     -1.988         9
518460      1.399  14.040000     -2.005         9
518461      1.399  14.048000     -2.001         9
518462      1.399  14.100000     -1.981         9
518463      1.400  14.064000     -1.997         9
518464      1.401  14.074000     -1.994         9
518465      1.403  14.089000     -1.974         9
518466      1.404  14.057000     -2.003         9
518467      1.404  14.088000     -1.969         9
518468      1.404  14.090000     -1.980         9
518469      1.405  14.054000     -2.007         9
518470      1.405  14.058000     -1.997         9
518471      1.407  14.081000     -1.995         9
518472      1.408  14.035000     -1.993         9
518473      1.411  14.062000     -2.002         9
518474      1.412  14.061000     -2.008         9
518475      1.413  14.030000     -1.999         9
518476      1.414  14.034000     -2.004         9
518477      1.419  14.025000     -2.002         9
518478      1.423  14.023000     -2.002         9
518479      1.428  14.014000     -2.001         9
518480      1.456  14.009000     -1.509         1
518481      1.468  13.979000     -1.521         1

[518482 rows x 4 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518482 entries, 0 to 518481
Data columns (total 4 columns):
-5.745000    518482 non-null float64
16.014999    518482 non-null float64
-1.555000    518482 non-null float64
9.000000     518482 non-null float64
dtypes: float64(4)
memory usage: 19.8 MB

In [8]:

data.describe()

           -5.745000      16.014999      -1.555000       9.000000
count  518482.000000  518482.000000  518482.000000  518482.000000
mean       -1.786923      16.129483       0.122075       5.527721
std         1.777820       1.093932       1.472509       2.201122
min        -5.745000      13.617000      -2.016000       1.000000
25%        -3.288000      15.549000      -1.313000       5.000000
50%        -1.437000      16.205999       0.064000       5.000000
75%        -0.323000      16.858999       1.235000       6.000000
max         1.468000      19.306000       3.823000       9.000000